ERROR - 2025-07-28 13:57:52 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\UserPetController.php(16): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\UserPetController.php(16): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-07-28 13:57:52 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\UserPetController.php(16): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-07-28 13:57:56 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(23): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(23): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-07-28 13:57:56 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\BookingController.php(23): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-07-28 13:58:01 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\UserPetController.php(16): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\UserPetController.php(16): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-07-28 13:58:01 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\UserPetController.php(16): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-07-28 13:58:05 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(23): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(23): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-07-28 13:58:05 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\BookingController.php(23): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-07-28 13:58:25 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(23): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(23): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-07-28 13:58:25 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\BookingController.php(23): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-07-28 13:58:29 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\UserPetController.php(16): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\UserPetController.php(16): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-07-28 13:58:29 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\UserPetController.php(16): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-07-28 14:00:22 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\UserPetController.php(16): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\UserPetController.php(16): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-07-28 14:00:22 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\UserPetController.php(16): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-07-28 14:00:26 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(23): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(23): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-07-28 14:00:26 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\BookingController.php(23): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-07-28 14:00:32 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(23): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(23): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-07-28 14:00:32 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\BookingController.php(23): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-07-28 14:00:36 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\UserPetController.php(16): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\UserPetController.php(16): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-07-28 14:00:36 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\UserPetController.php(16): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-07-28 14:00:49 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\system\Database\BaseBuilder.php(2395): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\app\Controllers\Workflow_User.php(99): CodeIgniter\Database\BaseBuilder->replace()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\Workflow_User->updateSpecificUser()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#7 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#8 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseBuilder.php(2395): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\Workflow_User.php(99): CodeIgniter\Database\BaseBuilder->replace()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\Workflow_User->updateSpecificUser()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2025-07-28 14:00:49 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2395): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH\Controllers\Workflow_User.php(99): CodeIgniter\Database\BaseBuilder->replace()
 4 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Workflow_User->updateSpecificUser()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-07-28 14:00:55 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\system\Database\BaseBuilder.php(2395): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\app\Controllers\Workflow_User.php(99): CodeIgniter\Database\BaseBuilder->replace()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\Workflow_User->updateSpecificUser()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#7 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#8 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseBuilder.php(2395): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\Workflow_User.php(99): CodeIgniter\Database\BaseBuilder->replace()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\Workflow_User->updateSpecificUser()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2025-07-28 14:00:55 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2395): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH\Controllers\Workflow_User.php(99): CodeIgniter\Database\BaseBuilder->replace()
 4 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Workflow_User->updateSpecificUser()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-07-28 14:01:53 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\UserPetController.php(16): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\UserPetController.php(16): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-07-28 14:01:53 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\UserPetController.php(16): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-07-28 14:01:57 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(23): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(23): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-07-28 14:01:57 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\BookingController.php(23): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-07-28 14:05:49 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(23): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(23): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-07-28 14:05:49 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\BookingController.php(23): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-07-28 14:05:54 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\UserPetController.php(16): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\UserPetController.php(16): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-07-28 14:05:54 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\UserPetController.php(16): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-07-28 14:06:45 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\UserPetController.php(16): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\UserPetController.php(16): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-07-28 14:06:45 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\UserPetController.php(16): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-07-28 14:06:49 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(23): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(23): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-07-28 14:06:49 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\BookingController.php(23): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-07-28 14:06:54 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(23): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(23): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-07-28 14:06:54 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\BookingController.php(23): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-07-28 14:06:58 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\UserPetController.php(16): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\UserPetController.php(16): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-07-28 14:06:58 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\UserPetController.php(16): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-07-28 14:07:43 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\UserPetController.php(16): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\UserPetController.php(16): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-07-28 14:07:43 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\UserPetController.php(16): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-07-28 14:07:47 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(42): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getDoctorLanguage()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(42): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getDoctorLanguage()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-07-28 14:07:47 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\BookingController.php(42): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\BookingController->getDoctorLanguage()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-07-28 14:07:48 --> Error connecting to the database: mysqli_sql_exception: Host 'localhost' is not allowed to connect to this MariaDB server in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(23): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Host 'localhost' is not allowed to connect to this MariaDB server in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(23): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-07-28 14:07:48 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Host 'localhost' is not allowed to connect to this MariaDB server
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\BookingController.php(23): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-07-28 14:07:55 --> Error connecting to the database: mysqli_sql_exception: Host 'localhost' is not allowed to connect to this MariaDB server in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(23): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Host 'localhost' is not allowed to connect to this MariaDB server in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(23): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-07-28 14:07:55 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Host 'localhost' is not allowed to connect to this MariaDB server
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\BookingController.php(23): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-07-28 14:07:55 --> Error connecting to the database: mysqli_sql_exception: Host 'localhost' is not allowed to connect to this MariaDB server in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(42): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getDoctorLanguage()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Host 'localhost' is not allowed to connect to this MariaDB server in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(42): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getDoctorLanguage()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-07-28 14:07:55 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Host 'localhost' is not allowed to connect to this MariaDB server
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\BookingController.php(42): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\BookingController->getDoctorLanguage()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-07-28 14:07:55 --> Error connecting to the database: mysqli_sql_exception: Host 'localhost' is not allowed to connect to this MariaDB server in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\UserPetController.php(16): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Host 'localhost' is not allowed to connect to this MariaDB server in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\UserPetController.php(16): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-07-28 14:07:55 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Host 'localhost' is not allowed to connect to this MariaDB server
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\UserPetController.php(16): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-07-28 14:08:03 --> Error connecting to the database: mysqli_sql_exception: Host 'localhost' is not allowed to connect to this MariaDB server in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(23): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Host 'localhost' is not allowed to connect to this MariaDB server in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(23): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-07-28 14:08:03 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Host 'localhost' is not allowed to connect to this MariaDB server
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\BookingController.php(23): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-07-28 14:08:03 --> Error connecting to the database: mysqli_sql_exception: Host 'localhost' is not allowed to connect to this MariaDB server in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\UserPetController.php(16): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Host 'localhost' is not allowed to connect to this MariaDB server in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\UserPetController.php(16): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-07-28 14:08:03 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Host 'localhost' is not allowed to connect to this MariaDB server
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\UserPetController.php(16): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-07-28 14:08:03 --> Error connecting to the database: mysqli_sql_exception: Host 'localhost' is not allowed to connect to this MariaDB server in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(42): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getDoctorLanguage()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Host 'localhost' is not allowed to connect to this MariaDB server in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(42): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getDoctorLanguage()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-07-28 14:08:03 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Host 'localhost' is not allowed to connect to this MariaDB server
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\BookingController.php(42): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\BookingController->getDoctorLanguage()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-07-28 14:08:27 --> Error connecting to the database: mysqli_sql_exception: Host 'localhost' is not allowed to connect to this MariaDB server in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(42): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getDoctorLanguage()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Host 'localhost' is not allowed to connect to this MariaDB server in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(42): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getDoctorLanguage()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-07-28 14:08:27 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Host 'localhost' is not allowed to connect to this MariaDB server
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\BookingController.php(42): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\BookingController->getDoctorLanguage()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-07-28 14:08:27 --> Error connecting to the database: mysqli_sql_exception: Host 'localhost' is not allowed to connect to this MariaDB server in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(23): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Host 'localhost' is not allowed to connect to this MariaDB server in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(23): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-07-28 14:08:27 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Host 'localhost' is not allowed to connect to this MariaDB server
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\BookingController.php(23): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-07-28 14:08:27 --> Error connecting to the database: mysqli_sql_exception: Host 'localhost' is not allowed to connect to this MariaDB server in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\UserPetController.php(16): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Host 'localhost' is not allowed to connect to this MariaDB server in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\UserPetController.php(16): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-07-28 14:08:27 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Host 'localhost' is not allowed to connect to this MariaDB server
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\UserPetController.php(16): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-07-28 14:08:36 --> Error connecting to the database: mysqli_sql_exception: Host 'localhost' is not allowed to connect to this MariaDB server in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\UserPetController.php(16): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Host 'localhost' is not allowed to connect to this MariaDB server in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\UserPetController.php(16): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-07-28 14:08:36 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Host 'localhost' is not allowed to connect to this MariaDB server
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\UserPetController.php(16): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-07-28 14:08:36 --> Error connecting to the database: mysqli_sql_exception: Host 'localhost' is not allowed to connect to this MariaDB server in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(23): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Host 'localhost' is not allowed to connect to this MariaDB server in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(23): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-07-28 14:08:36 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Host 'localhost' is not allowed to connect to this MariaDB server
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\BookingController.php(23): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-07-28 14:11:10 --> Error connecting to the database: mysqli_sql_exception: Host 'localhost' is not allowed to connect to this MariaDB server in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(42): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getDoctorLanguage()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Host 'localhost' is not allowed to connect to this MariaDB server in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(42): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getDoctorLanguage()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-07-28 14:11:10 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Host 'localhost' is not allowed to connect to this MariaDB server
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\BookingController.php(42): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\BookingController->getDoctorLanguage()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-07-28 14:11:11 --> Error connecting to the database: mysqli_sql_exception: Host 'localhost' is not allowed to connect to this MariaDB server in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(23): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Host 'localhost' is not allowed to connect to this MariaDB server in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(23): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-07-28 14:11:11 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Host 'localhost' is not allowed to connect to this MariaDB server
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\BookingController.php(23): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-07-28 14:11:11 --> Error connecting to the database: mysqli_sql_exception: Host 'localhost' is not allowed to connect to this MariaDB server in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\UserPetController.php(16): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Host 'localhost' is not allowed to connect to this MariaDB server in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\UserPetController.php(16): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-07-28 14:11:11 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Host 'localhost' is not allowed to connect to this MariaDB server
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\UserPetController.php(16): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-07-28 14:12:00 --> Error connecting to the database: mysqli_sql_exception: Host 'localhost' is not allowed to connect to this MariaDB server in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\system\Database\BaseBuilder.php(1749): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\app\Controllers\Workflow_User.php(56): CodeIgniter\Database\BaseBuilder->getWhere()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\Workflow_User->signupUser()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#7 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#8 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Host 'localhost' is not allowed to connect to this MariaDB server in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseBuilder.php(1749): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\Workflow_User.php(56): CodeIgniter\Database\BaseBuilder->getWhere()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\Workflow_User->signupUser()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2025-07-28 14:12:00 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Host 'localhost' is not allowed to connect to this MariaDB server
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1749): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH\Controllers\Workflow_User.php(56): CodeIgniter\Database\BaseBuilder->getWhere()
 4 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Workflow_User->signupUser()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
