ERROR - 2025-02-04 16:08:47 --> Error connecting to the database: ErrorException: mysqli::real_connect(): Error while reading greeting packet. PID=13484 in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#3 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\projects\Petz24\system\Database\BaseBuilder.php(1749): CodeIgniter\Database\BaseConnection->query()
#5 C:\xampp\htdocs\projects\Petz24\app\Controllers\Workflow_User.php(23): CodeIgniter\Database\BaseBuilder->getWhere()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\Workflow_User->signinuser()
#7 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#8 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#9 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next mysqli_sql_exception: MySQL server has gone away in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\system\Database\BaseBuilder.php(1749): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\app\Controllers\Workflow_User.php(23): CodeIgniter\Database\BaseBuilder->getWhere()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\Workflow_User->signinuser()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#7 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#8 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: MySQL server has gone away in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseBuilder.php(1749): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\Workflow_User.php(23): CodeIgniter\Database\BaseBuilder->getWhere()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\Workflow_User->signinuser()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2025-02-04 16:08:47 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: MySQL server has gone away
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1749): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH\Controllers\Workflow_User.php(23): CodeIgniter\Database\BaseBuilder->getWhere()
 4 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Workflow_User->signinuser()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-02-04 16:08:50 --> Error connecting to the database: ErrorException: mysqli::real_connect(): Error while reading greeting packet. PID=13484 in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#3 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\projects\Petz24\system\Database\BaseBuilder.php(1749): CodeIgniter\Database\BaseConnection->query()
#5 C:\xampp\htdocs\projects\Petz24\app\Controllers\Workflow_User.php(23): CodeIgniter\Database\BaseBuilder->getWhere()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\Workflow_User->signinuser()
#7 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#8 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#9 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next mysqli_sql_exception: MySQL server has gone away in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\system\Database\BaseBuilder.php(1749): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\app\Controllers\Workflow_User.php(23): CodeIgniter\Database\BaseBuilder->getWhere()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\Workflow_User->signinuser()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#7 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#8 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: MySQL server has gone away in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseBuilder.php(1749): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\Workflow_User.php(23): CodeIgniter\Database\BaseBuilder->getWhere()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\Workflow_User->signinuser()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2025-02-04 16:08:50 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: MySQL server has gone away
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1749): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH\Controllers\Workflow_User.php(23): CodeIgniter\Database\BaseBuilder->getWhere()
 4 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Workflow_User->signinuser()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-02-04 16:08:53 --> Error connecting to the database: ErrorException: mysqli::real_connect(): Error while reading greeting packet. PID=13484 in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#3 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\projects\Petz24\system\Database\BaseBuilder.php(1749): CodeIgniter\Database\BaseConnection->query()
#5 C:\xampp\htdocs\projects\Petz24\app\Controllers\Workflow_User.php(23): CodeIgniter\Database\BaseBuilder->getWhere()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\Workflow_User->signinuser()
#7 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#8 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#9 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next mysqli_sql_exception: MySQL server has gone away in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\system\Database\BaseBuilder.php(1749): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\app\Controllers\Workflow_User.php(23): CodeIgniter\Database\BaseBuilder->getWhere()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\Workflow_User->signinuser()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#7 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#8 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: MySQL server has gone away in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseBuilder.php(1749): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\Workflow_User.php(23): CodeIgniter\Database\BaseBuilder->getWhere()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\Workflow_User->signinuser()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2025-02-04 16:08:53 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: MySQL server has gone away
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1749): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH\Controllers\Workflow_User.php(23): CodeIgniter\Database\BaseBuilder->getWhere()
 4 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Workflow_User->signinuser()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-02-04 16:09:51 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\system\Database\BaseBuilder.php(1749): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\app\Controllers\Workflow_User.php(23): CodeIgniter\Database\BaseBuilder->getWhere()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\Workflow_User->signinuser()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#7 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#8 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseBuilder.php(1749): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\Workflow_User.php(23): CodeIgniter\Database\BaseBuilder->getWhere()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\Workflow_User->signinuser()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2025-02-04 16:09:51 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1749): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH\Controllers\Workflow_User.php(23): CodeIgniter\Database\BaseBuilder->getWhere()
 4 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Workflow_User->signinuser()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-02-04 16:12:03 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\system\Database\BaseBuilder.php(1749): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\app\Controllers\Workflow_User.php(23): CodeIgniter\Database\BaseBuilder->getWhere()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\Workflow_User->signinuser()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#7 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#8 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseBuilder.php(1749): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\Workflow_User.php(23): CodeIgniter\Database\BaseBuilder->getWhere()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\Workflow_User->signinuser()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2025-02-04 16:12:03 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1749): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH\Controllers\Workflow_User.php(23): CodeIgniter\Database\BaseBuilder->getWhere()
 4 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Workflow_User->signinuser()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-02-04 16:28:39 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(16): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(16): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-02-04 16:28:39 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\BookingController.php(16): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
